name: Check

on:
  push:
    branches: [ master ]

jobs:
  linux:
    name: Check latest commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.11'

      - name: Set up the build environment
        run: ./bootstrap.sh tools setup

      - name: Configure the build
        run: ./bootstrap.sh wk configure

      - name: Build the project
        run: ./bootstrap.sh wk build
